apiVersion: v1
kind: Service
metadata:
  name: {{ include "Worker.fullname" . }}
  labels:
    {{- include "Worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "Worker.selectorLabels" . | nindent 4 }}
