ARG DEBIAN_VERSION="latest"
ARG K3S_INSTALL_VERSION="v1.26.5+k3s1"
ARG KUBECTL_INSTALL_VERSION="v1.29"
ARG MICROSOFT_DEBIAN_VERSION="12"

FROM debian:${DEBIAN_VERSION}

RUN install -m 0755 -d /etc/apt/keyrings

# setup required services
RUN apt-get update -y
RUN apt-get install -y apt-transport-https ca-certificates curl wget git

# update apt source files
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
  | tee /etc/apt/sources.list.d/docker.list
RUN echo "deb [signed-by=/etc/apt/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$(. /etc/os-release && echo "Debian_$VERSION_ID")/ /" \
 | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
RUN echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/${KUBECTL_INSTALL_VERSION}/deb/ /' \
  | tee /etc/apt/sources.list.d/kubernetes.list
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/helm-apt-keyring.gpg] https://baltocdn.com/helm/stable/debian/ all main" \
  | tee /etc/apt/sources.list.d/helm-stable-debian.list

# setup docker apo key
RUN curl -fsSL https://download.docker.com/linux/debian/gpg \
  | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# setup cri-o apt key
RUN curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$(. /etc/os-release && echo "Debian_$VERSION_ID")/Release.key" \
  | gpg --dearmor -o /etc/apt/keyrings/libcontainers-archive-keyring.gpg

# setup kubectl apt key
RUN curl -fsSL "https://pkgs.k8s.io/core:/stable:/${KUBECTL_INSTALL_VERSION}/deb/Release.key" \
  | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# setup helm apt repo
RUN curl -fsSL https://baltocdn.com/helm/signing.asc \
  | gpg --dearmor -o /etc/apt/keyrings/helm-apt-keyring.gpg

# setup dotnet apt repo
RUN wget "https://packages.microsoft.com/config/debian/${MICROSOFT_DEBIAN_VERSION}/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

RUN apt-get update -y
RUN apt-get install -y docker docker-compose \
 cri-o cri-o-runc \
 skopeo podman buildah \
 kubectl \
 helm \
 powershell \
 dotnet-sdk-6.0 dotnet-sdk-7.0 dotnet-sdk-8.0

RUN apt-get -y autoremove
RUN apt-get -y autoclean

# setup k3s
RUN curl -Lo /usr/local/bin/k3s "https://github.com/k3s-io/k3s/releases/download/${K3S_INSTALL_VERSION}/k3s"
RUN chmod a+x /usr/local/bin/k3s

# setup dotnet tools
RUN dotnet tool restore

# setup helm unit test
RUN helm plugin install https://github.com/helm-unittest/helm-unittest.git
