version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: src/Api/Dockerfile
  frontend:
    build:
      context: ../
      dockerfile: src/Frontend/Dockerfile
  infra:
    build:
      context: ../
      dockerfile: src/Infrastructure/Dockerfile
  worker:
    build:
      context: ../
      dockerfile: src/Worker/Dockerfile
configs:
  api_appsettings:
    file: ../src/Api/appsettings.Development.json
  worker_appsettings:
    file: ../src/Api/appsettings.Development.json
  frontend_appsettings:
    file: ../src/Frontend/wwwroot/appsettings.Development.json
  infrastructure_appsettings:
    file: ../src/Infrastructure/appsettings.Development.json
secrets:
  api_secrets:
    file: ../secrets/api.json
  worker_secrets:
    file: ../secrets/worker.json