on: 
  pull_request:
    paths:
      - 'src/Api/**'
      - 'src/Api.Abstractions/**'
      - 'src/Api.Dto/**'
      - 'src/Api.Services/**'
      - 'src/Data.Dto/**'
      - 'src/Data/**'
      - 'test/Api.Test/**'
      - 'test/Data.Test/**'
      - 'test/Shared.Test/**'

jobs:
  dotnet-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: dotnet-lint
        run: ./dotnet-lint-api.sh
      - name: dotnet-build
        run: ./dotnet-build-api.sh
      - name: dotnet-unit-test
        run: ./unit-test-api.sh
  docker-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: docker-lint
        run: ./docker-lint-api.sh
      - name: docker-build
        run: ./docker-build-api.sh
      - name: dotnet-container-test
        run: ./container-test-api.sh
  helm-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

