on: 
  pull_request:
    paths:
      - 'k8s/**'
jobs:
  helm-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: helm-lint
        run: ./helm-lint.sh
      - name: helm-build
        run: ./helm-build.sh
      - name: helm-test
        run: ./helm-test.sh
