on:
  workflow_call:
    inputs:
      test-runner:
        required: false
        type: string
        default: ubuntu-latest
      concurrency-group:
        required: true
        type: string
    outputs:
      api:
        description: Did Api source code change?
        value: ${{ jobs.paths-filter.outputs.api }}
      api-test:
        description: Did Api test source code change?
        value: ${{ jobs.paths-filter.outputs.api-test }}
      api-docker:
        description: Did Api docker source code change?
        value: ${{ jobs.paths-filter.outputs.api-docker }}
      api-test-docker:
        description: Did Api test docker source code change?
        value: ${{ jobs.paths-filter.outputs.api-test-docker }}
      data: 
        description: Did Data source code change?
        value: ${{ jobs.paths-filter.outputs.data }}
      data-test: 
        description: Did Data test source code change?
        value: ${{ jobs.paths-filter.outputs.data }}
      docs: 
        description: Did documents source code change?
        value: ${{ jobs.paths-filter.outputs.docs }}
      docker:
        description: Did shared docker source code change?
        value: ${{ jobs.paths-filter.outputs.docker }}
      dotnet:
        description: Did dotnet source code change?
        value: ${{ jobs.paths-filter.outputs.dotnet }}
      e2e: 
        description: Did e2e source code change?
        value: ${{ jobs.paths-filter.outputs.e2e }}
      e2e-docker:
        description: Did e2e docker source code change?
        value: ${{ jobs.paths-filter.outputs.e2e-docker }}
      frontend: 
        description: Did frontend source code change?
        value: ${{ jobs.paths-filter.outputs.frontend }}
      frontend-test: 
        description: Did frontend test source code change?
        value: ${{ jobs.paths-filter.outputs.frontend-test }}
      frontend-docker:
        description: Did frontend docker source code change?
        value: ${{ jobs.paths-filter.outputs.frontend-docker }}
      frontend-docker-test:
        description: Did frontend test docker source code change?
        value: ${{ jobs.paths-filter.outputs.frontend-test-docker }}
      infra: 
        description: Did infrastructure source code change?
        value: ${{ jobs.paths-filter.outputs.infra }}
      infra-docker:
        description: Did infrastructure docker source code change?
        value: ${{ jobs.paths-filter.outputs.infra-docker }}
      infra-test: 
        description: Did infrastructure test source code change?
        value: ${{ jobs.paths-filter.outputs.infra-test }}
      infra-test-docker:
        description: Did infrastructure test docker source code change?
        value: ${{ jobs.paths-filter.outputs.infra-test-docker }}
      k8s: 
        description: Did k8s source code change?
        value: ${{ jobs.paths-filter.outputs.k8s }}
      migration: 
        description: Did data migration source code change?
        value: ${{ jobs.paths-filter.outputs.migration }}
      packages: 
        description: Did the packages change?
        value: ${{ jobs.paths-filter.outputs.packages }}
      worker: 
        description: Did worker source code change?
        value: ${{ jobs.paths-filter.outputs.worker }}
      worker-docker:
        description: Did worker docker source code change?
        value: ${{ jobs.paths-filter.outputs.worker-docker }}
      worker-test: 
        description: Did worker test source code change?
        value: ${{ jobs.paths-filter.outputs.worker }}
      worker-test-docker:
        description: Did worker test docker source code change?
        value: ${{ jobs.paths-filter.outputs.worker-test-docker }}
      workflows: 
        description: Did workflow source code change?
        value: ${{ jobs.paths-filter.outputs.workflows }}
jobs:
# job generate variables to filter
  paths-filter:
    runs-on: {{ inputs.test-runner }}
    outputs:
      api: ${{ steps.filter.outputs.api }}
      api-docker: ${{ steps.filter.outputs.api-docker }}
      api-test: ${{ steps.filter.outputs.api-test }}
      api-test-docker: ${{ steps.filter.outputs.api-test-docker }}
      data: ${{ steps.filter.outputs.data }}
      data-test: ${{ steps.filter.outputs.data-test }}
      dotnet: ${{ steps.filter.outputs.dotnet }}
      e2e: ${{ steps.filter.outputs.e2e }}
      e2e-docker: ${{ steps.filter.outputs.e2e-docker }}
      frontend: ${{ steps.filter.outputs.frontend }}
      frontend-test: ${{ steps.filter.outputs.frontend-test }}
      frontend-docker: ${{ steps.filter.outputs.frontend-docker }}
      frontend-test-docker: ${{ steps.filter.outputs.frontend-test-docker }}
      infra: ${{ steps.filter.outputs.infra }}
      infra-test: ${{ steps.filter.outputs.infra-test }}
      infra-docker: ${{ steps.filter.outputs.infra-docker }}
      infra-docker-test: ${{ steps.filter.outputs.infra-docker-test }}
      k8s: ${{ steps.filter.outputs.k8s }}
      migration: ${{ steps.filter.outputs.migration }}
      packages: ${{ steps.filter.outputs.packages }}
      worker: ${{ steps.filter.outputs.worker }}
      worker-test: ${{ steps.filter.outputs.worker-test }}
      worker-docker: ${{ steps.filter.outputs.worker-docker }}
      worker-test-docker: ${{ steps.filter.outputs.worker-test-docker }}
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          api:
            - 'src/Api/**'
            - 'src/Api.Abstractions/**'
            - 'src/Api.Dto/**'
            - 'src/Api.Services/**'
            - 'src/Data/**'
            - 'src/Data.Dto/**'
            - 'test/Api.Test/**'
            - 'test/Data.Seed.Test/**'
            - 'test/Shared.Test/**'
            - '!src/Api/Containerfile'
            - '!test/Api.Test/Containerfile'
          api-test:
            - 'test/Api.Test/**'
            - 'test/Data.Seed.Test/**'
            - 'test/Shared.Test/**'
            - '!test/Api.Test/Containerfile'
          api-docker:
            - 'src/Api/Containerfile'
          data:
            - 'src/Data/**'
            - 'src/Data.Dto/**'
            - 'test/Data.Seed.Test/**'
            - 'test/Data.Test/**'
          data-test:
            - 'test/Data.Seed.Test/**'
            - 'test/Data.Test/**'
            - 'test/Shared.Test/**'
          dotnet: 
            - 'src/**/*.cs'
            - 'test/**/*.cs'
            - 'src/**/*.razor'
            - 'src/**/*.cshtml'
            - 'src/**/*.csproj'
            - 'test/**/*.csproj'
            - '*.sln'
            - '*.props'
            - 'src/*.props'
            - 'test/*.props'
          migration:
            - 'src/Data/Migrations/**'
          packages:
            - 'src/**/packages.lock.json'
            - 'test/**/packages.lock.json'
          docker:
            - 'scripts/docker-compose.*.yml'
            - 'scripts/docker-compose.yml'
            - 'scripts/.env'
            - '.dockerignore'
          docs:
            - '.github/docs/**'
            - 'README.md'
          e2e:
            - 'src/Api.Dto/**'
            - 'src/Data/**'
            - 'src/Data.Dto/**'
            - 'test/Data.Seed.Test/**'
            - 'test/E2E.Test/**'
            - 'test/Data.Seed.Test/**'
            - 'test/Shared.Test/**'
            - '!test/E2E.Test/Containerfile'
          e2e-docker:
            - 'test/E2E.Test/Containerfile'
          frontend:
            - 'src/Api.Dto/**'
            - 'src/Frontend/**'
            - '!src/Frontend/Containerfile'
          frontend-test:
            - 'test/Frontend.Test/**'
            - 'test/Shared.Test/**'
            - '!test/Frontend.Test/Containerfile'
          frontend-test-docker:
            - 'test/Frontend.Test/Containerfile'
          frontend-docker:
            - 'src/Frontend/Containerfile'
          infra:
            - 'src/Infrastructure/**'
            - '!src/Infrastructure/Containerfile'
          infra-docker:
            - 'src/Infrastructure/Containerfile'
          infra-test:
            - 'test/Infrastructure.Test/**'
            - '!test/Infrastructure.Test/Containerfile'
          infra-test-docker:
            - 'test/Infrastructure.Test/Containerfile'
          k8s:
            - 'k8s/**'
          worker:
            - 'src/Data/**'
            - 'src/Data.Dto/**'
            - 'src/Worker/**'
            - 'src/Worker.Abstractions/**'
            - 'src/Worker.Dto/**'
            - 'src/Worker.Services/**'
            - '!src/Worker/Containerfile'
          worker-docker:
            - 'src/Worker/Containerfile'
          worker-test:
            - 'test/Data.Seed.Test/**'
            - 'test/Shared.Test/**'
            - 'test/Worker.Test/**'
            - '!test/Worker.Test/Containerfile'
          worker-test-docker:
            - 'test/Worker.Test/Containerfile'
          workflows:
            - '.github/workflows/**'