on: 
  workflow_call:
    inputs:
      cache-name:
        required: false
        type: string
        default: default
      concurrency-group:
        required: true
        type: string
      test-runner:
        required: false
        type: string
        default: ubuntu-latest
      dotnet-version:
        required: false
        type: string
        default: '7.x'
      dotnet-setup:
        required: false
        type: boolean
        default: true
    outputs:
      cache-key: ${{ jobs.shared-cache.outputs.cache-key }}
      cache-updated: ${{ jobs.shared-cache.outputs.cache-updated}}
jobs:
  shared-cache:
    runs-on: ${{ inputs.test-runner }}
    outputs:
      cache-key: ${{ steps.restore-cache.outputs.cache-primary-key }}
    steps:
      - name: git-checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/**/packages.lock.json
            test/**/packages.lock.json
            src/**/*.csproj
            test/**/*.csproj
            src/**/*.props
            test/**/*.props
            *.props
            Example.sln
      - name: dotnet-setup
        if: ${{ inputs.dotnet-setup }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: dotnet-cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ inputs.cache-name }}-${{ hashFiles('**/packages.lock.json') }}
      - name: dotnet-restore
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: dotnet restore --locked-mode
      - name: dotnet-save-cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.nuget/packages
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
      - name: dotnet-cache-updated
        run: echo "cache-updated=${{ steps.restore-cache.outputs.cache-hit }}" >> $GITHUB_OUTPUTS