on: 
  workflow_call:
    inputs:
      image-repo:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      test-runner:
        required: false
        type: string
        default: ubuntu-latest
permissions:
  contents: read
  packages: write
jobs:
  image-clean-up:
    runs-on: ${{ inputs.test-runner }}
    steps:
      - name: delete-container-image
        uses: actions/delete-package-versions@v4
        with:
          package-version-ids: ${{ inputs.image-tag }}
          package-name: ${{ inputs.image-repo }}/${{ inputs.image-name }}
          package-type: container

    