on:
  workflow_dispatch:
    inputs:
      e2e-test:
        description: Run E2E tests
        required: false
        type: boolean
        default: false
      integration-test:
        description: Run Integration tests
        required: false
        type: boolean
        default: false
      unit-test:
        description: Run Unit tests
        required: false
        type: boolean
        default: false
jobs:
  ci-build:
    uses: './.github/workflows/ci-build.yml'
    with:
      test-runner: ubuntu-latest
      concurrency-group: ${{ github.workflow }}-${{ github.ref }}
      image-repo: ghrc.io/${{ github.organisation }}
      chart-repo: ghrc.io/${{ github.organisation }}
      chart-name: test-containers-example-chart
      chart-version: pr-${{ github.workflow }}-${{ github.ref }}-${{ github.run_number }}
      image-tag: pr-${{ github.workflow }}-${{ github.ref }}-${{ github.run_number }}
      publish-chart: true
      publish-image: true
      api-image-name: test-containers-api
      api-test-image-name: test-containers-api-tests
      worker-image-name: test-containers-worker
      worker-test-image-name: test-containers-worker-tests
      data-test-image-name: test-containers-data-tests
      frontend-image-name: test-containers-frontend
      frontend-test-image-name: test-containers-frontend-tests
      
      
  